name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jodersky/setup-mill@master
        with:
          mill-version: 0.9.9
      - name: Compile all
        run: mill _.compile 
      - name: Test all
        run: mill _.test